# -*- coding: utf-8 -*-
"""Plot analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AvQnjdFU7neAcPDq41fXpJfjcemCz8mO
"""

import pandas as pd
import numpy as np
import plotly.express as px

#Reading the dataset
apps = pd.read_csv('../Top-Apps-in-Google-Play.csv')

#Column Reference:

#In app purchases:
#In-app purchasing refers to the buying of goods and services from 
#inside an application on a mobile device, such as a smartphone or tablet. 
#In-app purchases allow developers to provide their applications for free. (from investopedia.com)

#Ad supported:
#Software that is paid for by advertisers. Pure ad-supported applications and 
#websites always generate ads. In contrast, freemium products that display ads 
#will stop the advertising when the user pays a fee. (from pcmag.com)

#Dropping some columns that aren't usefull right now
apps = apps.drop(['Unnamed: 0', 'App Id', 'Developer Website', 'Developer Email'], axis=1)

#Replacing boolean values to 0 and 1. 0 for False and 1 for True.
apps[['Ad Supported','In App Purchases']] = apps[['Ad Supported','In App Purchases']].replace(to_replace=[False, True], value=[0,1])
apps.sample(20)

#Dataframe of  in purchasing apps:
purchase = apps[apps['In App Purchases']==1][['App Name','Category', 'Developer Id', 'Content Rating', 'Ad Supported']]

#Dataframe of add supported apps:
ad = apps[apps['Ad Supported']==1][['App Name','Category', 'Developer Id', 'Content Rating', 'In App Purchases']]

#Dataframe of in purchasing and ad supported apps:
purchase_ad = purchase[purchase['Ad Supported']==1][['App Name','Category', 'Developer Id', 'Content Rating']]

#Dataframe of apps that are not in purchasig:
not_purchase = apps[apps['In App Purchases']==0][['App Name','Category', 'Developer Id', 'Content Rating', 'Ad Supported']]

#Dataframe of apps that are not ad supported:
not_ad = apps[apps['Ad Supported']==0][['App Name','Category', 'Developer Id', 'Content Rating', 'In App Purchases']]

#Dataframe of not ad supported apps that also are not in purchase
not_purchase_not_ad = not_purchase[not_purchase['Ad Supported']==0][['App Name','Category', 'Developer Id', 'Content Rating']]

#Plotting the not_purchase_not_ad dataframe:
fig1=px.pie(not_purchase_not_ad, names='Developer Id', title='Apps that are not in purchase and ad supported - Developer Id', 
       color_discrete_sequence=['#bbd0f7','#76a0ef','#3271e7','#1344a0','#0b275b','#030a17'], width=800, height=600)
fig2=px.pie(not_purchase_not_ad, names='Content Rating', title='Apps that are not in purchase and ad supported - Content Rating', width=800, height=600)
fig3=px.pie(not_purchase_not_ad, names='Category', title='Apps that are not in purchase and ad supported - Category', width=800, height=600)

fig1.show()
fig2.show()
fig3.show()

#Plotting intersections in the not_purchase_not_ad dataframe:

fig4=px.bar(not_purchase_not_ad, x='Developer Id', color='Category')
fig5=px.bar(not_purchase_not_ad, x='Category', color='Content Rating')

fig4.show()
fig5.show()

#Plotting the purchase_ad dataframe:

fig6=px.pie(purchase_ad, names='Developer Id', title='In purchase and ad supported apps - Developer Id', 
       color_discrete_sequence=['#bbd0f7','#76a0ef','#3271e7','#1344a0','#0b275b','#030a17'], width=800, height=600)
fig7=px.pie(purchase_ad, names='Content Rating', title='In purchase and ad supported apps - Content Rating', width=800, height=600)
fig8=px.pie(purchase_ad, names='Category', title='In purchase and ad supported apps - Category', width=800, height=600)

fig6.show()
fig7.show()
fig8.show()

#Plotting intersections in the purchase_ad dataframe:

fig9=px.bar(purchase_ad, x='Developer Id', color='Category')
fig10=px.bar(purchase_ad, x='Category', color='Content Rating')

fig9.show()
fig10.show()

#Plotting the ad dataframe:
fig11=px.pie(ad, names='Developer Id', title='Ad supported apps - Developer Id', 
       color_discrete_sequence=['#bbd0f7','#76a0ef','#3271e7','#1344a0','#0b275b','#030a17'], width=800, height=600)
fig12=px.pie(ad, names='Content Rating', title='Ad supported apps - Content Rating', width=800, height=600)
fig13=px.pie(ad, names='Category', title='Ad supported apps - Category', width=800, height=600)

fig11.show()
fig12.show()
fig13.show()

#Plotting the purchase dataframe:
fig16=px.pie(purchase, names='Developer Id', title='In app purchase - Developer Id', 
       color_discrete_sequence=['#bbd0f7','#76a0ef','#3271e7','#1344a0','#0b275b','#030a17'], width=800, height=600)
fig17=px.pie(purchase, names='Content Rating', title='In app purchase - Content Rating', width=800, height=600)
fig18=px.pie(purchase, names='Category', title='In app purchase - Category', width=800, height=600)

fig16.show()
fig17.show()
fig18.show()

#Plotting intersections in the purchase dataframe:

fig19=px.bar(purchase, x='Developer Id', color='Category')
fig20=px.bar(purchase, x='Category', color='Content Rating')

fig19.show()
fig20.show()
